"""Shared, runtime-agnostic kubernetes rendering helpers.

Used by every runtime adapter (hermes, claude-code, codex) that materializes a
scoped RBAC identity + kubeconfig for a Binding, and also renders the
`access: inherit` overlay script shared across all three. Keeping this module
free of runtime-specific concepts keeps the engine-neutral rule intact: only
`src/aoh/adapters/<runtime>.py` files know about a specific agent runtime.
"""

from __future__ import annotations

import re
import shlex

from aoh.pack import Binding, PackError


READONLY_VERBS = ("get", "list", "watch")

INHERIT_DIAGNOSTIC = (
    "access=inherit: no RBAC boundary — agent acts with the user's "
    "credentials, context-pinned only"
)

KUBECTL_READ_COMMANDS = (
    "get",
    "describe",
    "logs",
    "top",
    "events",
    "explain",
    "api-resources",
    "api-versions",
    "version",
    "auth can-i",
)

KUBECTL_MUTATION_COMMANDS = (
    "delete",
    "apply",
    "edit",
    "patch",
    "replace",
    "create",
    "drain",
    "cordon",
    "uncordon",
    "taint",
    "scale",
    "rollout",
    "set",
    "annotate",
    "label",
    "expose",
    "run",
    "debug",
    "autoscale",
    "exec",
    "attach",
    "port-forward",
    "cp",
    "certificate",
)


_DNS_1123_LABEL_RE = re.compile(r"^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$")
_KUBE_CONTEXT_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9:/._@-]*$")


def kubeconfig_merge_shell_expr(workspace_dir_var: str = "$DIR") -> str:
    """Shell-context KUBECONFIG merge expression for `access: inherit` mode.

    SHELL ONLY — never place this in a JSON/TOML `env` block. Those are
    literal values with no shell expansion, and (for Claude Code) `env`
    entries in settings.json OVERRIDE shell exports rather than merge with
    them. Putting this expression there does not just fail to expand — it
    silently replaces the correctly-expanded launch.sh export with a dead
    literal string, breaking kubectl in-session. This function exists so the
    one correct shell-context expression is defined once and reused by every
    launch.sh renderer instead of being hand-duplicated per adapter.
    """
    return f'{workspace_dir_var}/kubeconfig-overlay:${{KUBECONFIG:-$HOME/.kube/config}}'


def validate_binding_fields(binding: Binding) -> None:
    """Validate binding name/namespace/kubeContext with per-field allowlists.

    Raises PackError with a field-appropriate message on invalid input. This
    replaces a single shared regex with rules that fit each field: name and
    namespace are DNS-1123 labels (name becomes a ServiceAccount name);
    kubeContext allows the wider charset needed by EKS-style ARNs while still
    excluding shell metacharacters.
    """

    namespace = str(binding.target.get("namespace", "default"))
    kube_context = str(binding.target.get("kubeContext", ""))

    for label, value in (
        ("metadata.name", binding.name),
        ("target.namespace", namespace),
    ):
        if not _DNS_1123_LABEL_RE.fullmatch(value):
            raise PackError(
                f"Binding `{binding.name}` {label} must be a DNS-1123 label "
                "(lowercase alphanumerics and dashes, must start/end alphanumeric)"
            )

    if not _KUBE_CONTEXT_RE.fullmatch(kube_context):
        raise PackError(
            f"Binding `{binding.name}` target.kubeContext contains unsafe characters "
            "(allowed: alphanumerics and : / . _ @ -)"
        )


def render_provision_script(binding: Binding) -> str:
    """Render the scoped-mode provision script for a binding.

    Provisions a read-only ServiceAccount bound to an explicit RBAC allowlist
    (never a `*/*` wildcard), then writes a scoped kubeconfig next to the
    script. Shared across every runtime adapter — the RBAC surface an agent
    gets must not depend on which agent runtime it is running under.
    """

    context = str(binding.target.get("kubeContext"))
    namespace = str(binding.target.get("namespace", "default"))
    sa_name = f"aoh-{binding.name}"

    context_q = shlex.quote(context)
    namespace_q = shlex.quote(namespace)
    sa_name_q = shlex.quote(sa_name)

    return f'''#!/usr/bin/env bash
set -euo pipefail

# Generated by AOH for binding `{binding.name}`.
# Provisions a READ-ONLY RBAC identity for the agent, then writes a scoped
# kubeconfig next to this script. Run ONCE with admin access to the target
# cluster. AOH never executes this script; you do. Re-running is safe.

CONTEXT={context_q}
NAMESPACE={namespace_q}
SA_NAME={sa_name_q}
PROFILE_DIR="$(cd "$(dirname "$0")" && pwd)"
KUBECONFIG_OUT="${{PROFILE_DIR}}/kubeconfig"
MANIFEST_OUT="${{PROFILE_DIR}}/aoh-provision.json"

kubectl --context "${{CONTEXT}}" -n "${{NAMESPACE}}" create serviceaccount "${{SA_NAME}}" \\
  --dry-run=client -o yaml | kubectl --context "${{CONTEXT}}" apply -f -

kubectl --context "${{CONTEXT}}" apply -f - <<'RBAC'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aoh-readonly
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/log", "events", "endpoints", "services",
                "persistentvolumeclaims", "persistentvolumes", "namespaces",
                "replicationcontrollers", "resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
RBAC

kubectl --context "${{CONTEXT}}" apply -f - <<RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aoh-readonly-${{SA_NAME}}
subjects:
  - kind: ServiceAccount
    name: ${{SA_NAME}}
    namespace: ${{NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: aoh-readonly
  apiGroup: rbac.authorization.k8s.io
RBAC

TOKEN="$(kubectl --context "${{CONTEXT}}" -n "${{NAMESPACE}}" create token "${{SA_NAME}}" --duration=720h)"
SERVER="$(kubectl config view --minify --context "${{CONTEXT}}" -o jsonpath='{{.clusters[0].cluster.server}}')"
CA_DATA="$(kubectl config view --minify --raw --context "${{CONTEXT}}" -o jsonpath='{{.clusters[0].cluster.certificate-authority-data}}')"
TOKEN_EXPIRES_AT="$(date -u -v+720H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "+720 hours" +%Y-%m-%dT%H:%M:%SZ)"

if [[ -z "${{CA_DATA}}" ]]; then
  echo "ERROR: could not read certificate-authority-data from context ${{CONTEXT}}." >&2
  echo "Inline CA data is required (kind provides it by default)." >&2
  exit 1
fi

cat > "${{KUBECONFIG_OUT}}" <<KCFG
apiVersion: v1
kind: Config
clusters:
  - name: ${{CONTEXT}}
    cluster:
      server: ${{SERVER}}
      certificate-authority-data: ${{CA_DATA}}
contexts:
  - name: ${{CONTEXT}}
    context:
      cluster: ${{CONTEXT}}
      user: ${{SA_NAME}}
      namespace: ${{NAMESPACE}}
current-context: ${{CONTEXT}}
users:
  - name: ${{SA_NAME}}
    user:
      token: ${{TOKEN}}
KCFG
chmod 600 "${{KUBECONFIG_OUT}}"

cat > "${{MANIFEST_OUT}}" <<MANIFEST
{{
  "server": "${{SERVER}}",
  "serviceAccount": "${{SA_NAME}}",
  "context": "${{CONTEXT}}",
  "namespace": "${{NAMESPACE}}",
  "tokenExpiresAt": "${{TOKEN_EXPIRES_AT}}"
}}
MANIFEST

echo "Scoped read-only kubeconfig written to ${{KUBECONFIG_OUT}}"
echo "Verify the guardrail: kubectl --kubeconfig ${{KUBECONFIG_OUT}} delete pod x  # expect Forbidden"
'''


def render_overlay_prepare_script(binding: Binding) -> str:
    """Render the inherit-mode overlay preparation script for a binding.

    `access: inherit` means the agent acts with the USER's own kubeconfig
    credentials — there is no scoped RBAC identity and no hard enforcement
    boundary. AOH never copies or snapshots credentials for this mode: the
    generated `prepare-overlay.sh` only RESOLVES the target context's
    cluster/user entry *names* from the user's merged kubeconfig (via a
    redacted `kubectl config view` — NEVER `--raw`, which would print
    embedded credential material), then writes a minimal `kubeconfig-overlay`
    that pins `current-context` + a context entry referencing those resolved
    names + the binding's namespace. Actual credentials stay wherever the
    user's own kubeconfig/exec-plugins already keep them; the overlay is
    merged in front of the user's file via KUBECONFIG (first file wins for
    current-context, but cluster/user references still resolve against the
    user's file, so exec-plugin auth like gke-gcloud-auth-plugin keeps
    working).

    The script verifies itself twice before declaring success:
      1. `kubectl config view --minify` against the merged KUBECONFIG must
         resolve the pinned context, or it exits 1 with a clear error.
      2. It greps its OWN generated overlay file for credential-shaped
         content (`client-key-data`, `client-certificate-data`, `token:`)
         and exits 1 if any is found — belt-and-braces, since step (1)'s
         resolution already should not have written any.
    """

    context = str(binding.target.get("kubeContext"))
    namespace = str(binding.target.get("namespace", "default"))

    context_q = shlex.quote(context)
    namespace_q = shlex.quote(namespace)

    return f'''#!/usr/bin/env bash
set -euo pipefail

# Generated by AOH for binding `{binding.name}` (access: inherit).
#
# access=inherit means the agent acts with YOUR OWN kubeconfig credentials —
# there is NO scoped RBAC identity and NO hard enforcement boundary in this
# mode. This script never copies, snapshots, or writes any credential
# material. It only RESOLVES the target context's cluster/user entry NAMES
# from a REDACTED kubectl config view (the unredacted flag that would print
# embedded secrets is never used) and writes a small overlay file that pins
# current-context + namespace. Your actual credentials stay exactly where
# they already are. AOH never executes this script; you do. Re-running is
# safe.

CONTEXT={context_q}
NAMESPACE={namespace_q}
PROFILE_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${{PROFILE_DIR}}/kubeconfig-overlay"
SRC="${{KUBECONFIG:-$HOME/.kube/config}}"

CLUSTER_NAME="$(kubectl config view -o jsonpath="{{.contexts[?(@.name==\\"${{CONTEXT}}\\")].context.cluster}}")"
USER_NAME="$(kubectl config view -o jsonpath="{{.contexts[?(@.name==\\"${{CONTEXT}}\\")].context.user}}")"

if [[ -z "${{CLUSTER_NAME}}" || -z "${{USER_NAME}}" ]]; then
  echo "ERROR: could not resolve context ${{CONTEXT}} in your kubeconfig (${{SRC}})." >&2
  echo "Check that the context exists: kubectl config get-contexts" >&2
  exit 1
fi

cat > "${{OUT}}" <<KCFG
apiVersion: v1
kind: Config
contexts:
  - name: ${{CONTEXT}}
    context:
      cluster: ${{CLUSTER_NAME}}
      user: ${{USER_NAME}}
      namespace: ${{NAMESPACE}}
current-context: ${{CONTEXT}}
KCFG

# Verify: the merged KUBECONFIG (overlay in front of the user's own file)
# must resolve this context cleanly via `kubectl config view --minify`.
if ! KUBECONFIG="${{OUT}}:${{SRC}}" kubectl config view --minify >/dev/null 2>&1; then
  echo "ERROR: overlay kubeconfig failed to resolve via 'kubectl config view --minify'." >&2
  echo "KUBECONFIG=${{OUT}}:${{SRC}}" >&2
  exit 1
fi

# Self-check: the overlay we just wrote must contain NO credential material.
# Belt-and-braces — step above never writes any, this proves it.
if command grep -Eq 'client-key-data|client-certificate-data|token:' "${{OUT}}"; then
  echo "ERROR: overlay kubeconfig unexpectedly contains credential-shaped data; refusing to proceed." >&2
  exit 1
fi

echo "Overlay kubeconfig written to ${{OUT}} (no credentials copied)"
echo "Launch with: KUBECONFIG=\\"${{OUT}}:\\${{KUBECONFIG:-\\$HOME/.kube/config}}\\" <agent>"
'''
