"""Shared, runtime-agnostic kubernetes rendering helpers.

Used by every runtime adapter (hermes, claude-code, codex) that materializes a
scoped RBAC identity + kubeconfig for a Binding. Keeping this module free of
runtime-specific concepts keeps the engine-neutral rule intact: only
`src/aoh/adapters/<runtime>.py` files know about a specific agent runtime.
"""

from __future__ import annotations

import re
import shlex

from aoh.pack import Binding, PackError


READONLY_VERBS = ("get", "list", "watch")

KUBECTL_READ_COMMANDS = (
    "get",
    "describe",
    "logs",
    "top",
    "events",
    "explain",
    "api-resources",
    "api-versions",
    "version",
    "auth can-i",
)

KUBECTL_MUTATION_COMMANDS = (
    "delete",
    "apply",
    "edit",
    "patch",
    "replace",
    "create",
    "drain",
    "cordon",
    "uncordon",
    "taint",
    "scale",
    "rollout",
    "set",
    "annotate",
    "label",
    "expose",
    "run",
    "debug",
    "autoscale",
    "exec",
    "attach",
    "port-forward",
    "cp",
    "certificate",
)


_DNS_1123_LABEL_RE = re.compile(r"^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$")
_KUBE_CONTEXT_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9:/._@-]*$")


def validate_binding_fields(binding: Binding) -> None:
    """Validate binding name/namespace/kubeContext with per-field allowlists.

    Raises PackError with a field-appropriate message on invalid input. This
    replaces a single shared regex with rules that fit each field: name and
    namespace are DNS-1123 labels (name becomes a ServiceAccount name);
    kubeContext allows the wider charset needed by EKS-style ARNs while still
    excluding shell metacharacters.
    """

    namespace = str(binding.target.get("namespace", "default"))
    kube_context = str(binding.target.get("kubeContext", ""))

    for label, value in (
        ("metadata.name", binding.name),
        ("target.namespace", namespace),
    ):
        if not _DNS_1123_LABEL_RE.fullmatch(value):
            raise PackError(
                f"Binding `{binding.name}` {label} must be a DNS-1123 label "
                "(lowercase alphanumerics and dashes, must start/end alphanumeric)"
            )

    if not _KUBE_CONTEXT_RE.fullmatch(kube_context):
        raise PackError(
            f"Binding `{binding.name}` target.kubeContext contains unsafe characters "
            "(allowed: alphanumerics and : / . _ @ -)"
        )


def render_provision_script(binding: Binding) -> str:
    """Render the scoped-mode provision script for a binding.

    Provisions a read-only ServiceAccount bound to an explicit RBAC allowlist
    (never a `*/*` wildcard), then writes a scoped kubeconfig next to the
    script. Shared across every runtime adapter — the RBAC surface an agent
    gets must not depend on which agent runtime it is running under.
    """

    context = str(binding.target.get("kubeContext"))
    namespace = str(binding.target.get("namespace", "default"))
    sa_name = f"aoh-{binding.name}"

    context_q = shlex.quote(context)
    namespace_q = shlex.quote(namespace)
    sa_name_q = shlex.quote(sa_name)

    return f'''#!/usr/bin/env bash
set -euo pipefail

# Generated by AOH for binding `{binding.name}`.
# Provisions a READ-ONLY RBAC identity for the agent, then writes a scoped
# kubeconfig next to this script. Run ONCE with admin access to the target
# cluster. AOH never executes this script; you do. Re-running is safe.

CONTEXT={context_q}
NAMESPACE={namespace_q}
SA_NAME={sa_name_q}
PROFILE_DIR="$(cd "$(dirname "$0")" && pwd)"
KUBECONFIG_OUT="${{PROFILE_DIR}}/kubeconfig"
MANIFEST_OUT="${{PROFILE_DIR}}/aoh-provision.json"

kubectl --context "${{CONTEXT}}" -n "${{NAMESPACE}}" create serviceaccount "${{SA_NAME}}" \\
  --dry-run=client -o yaml | kubectl --context "${{CONTEXT}}" apply -f -

kubectl --context "${{CONTEXT}}" apply -f - <<'RBAC'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aoh-readonly
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/log", "events", "endpoints", "services",
                "persistentvolumeclaims", "persistentvolumes", "namespaces",
                "replicationcontrollers", "resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
RBAC

kubectl --context "${{CONTEXT}}" apply -f - <<RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aoh-readonly-${{SA_NAME}}
subjects:
  - kind: ServiceAccount
    name: ${{SA_NAME}}
    namespace: ${{NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: aoh-readonly
  apiGroup: rbac.authorization.k8s.io
RBAC

TOKEN="$(kubectl --context "${{CONTEXT}}" -n "${{NAMESPACE}}" create token "${{SA_NAME}}" --duration=720h)"
SERVER="$(kubectl config view --minify --context "${{CONTEXT}}" -o jsonpath='{{.clusters[0].cluster.server}}')"
CA_DATA="$(kubectl config view --minify --raw --context "${{CONTEXT}}" -o jsonpath='{{.clusters[0].cluster.certificate-authority-data}}')"
TOKEN_EXPIRES_AT="$(date -u -v+720H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "+720 hours" +%Y-%m-%dT%H:%M:%SZ)"

if [[ -z "${{CA_DATA}}" ]]; then
  echo "ERROR: could not read certificate-authority-data from context ${{CONTEXT}}." >&2
  echo "Inline CA data is required (kind provides it by default)." >&2
  exit 1
fi

cat > "${{KUBECONFIG_OUT}}" <<KCFG
apiVersion: v1
kind: Config
clusters:
  - name: ${{CONTEXT}}
    cluster:
      server: ${{SERVER}}
      certificate-authority-data: ${{CA_DATA}}
contexts:
  - name: ${{CONTEXT}}
    context:
      cluster: ${{CONTEXT}}
      user: ${{SA_NAME}}
      namespace: ${{NAMESPACE}}
current-context: ${{CONTEXT}}
users:
  - name: ${{SA_NAME}}
    user:
      token: ${{TOKEN}}
KCFG
chmod 600 "${{KUBECONFIG_OUT}}"

cat > "${{MANIFEST_OUT}}" <<MANIFEST
{{
  "server": "${{SERVER}}",
  "serviceAccount": "${{SA_NAME}}",
  "context": "${{CONTEXT}}",
  "namespace": "${{NAMESPACE}}",
  "tokenExpiresAt": "${{TOKEN_EXPIRES_AT}}"
}}
MANIFEST

echo "Scoped read-only kubeconfig written to ${{KUBECONFIG_OUT}}"
echo "Verify the guardrail: kubectl --kubeconfig ${{KUBECONFIG_OUT}} delete pod x  # expect Forbidden"
'''


def render_overlay_note() -> str:
    """Placeholder for the inherit-mode overlay renderer (added in Task 5)."""

    raise NotImplementedError("render_overlay_note is implemented in a later task")
